### PR TITLE
Update equinix terraform provider to v3.0.0

### PR DESCRIPTION
**Pull request by rajeshkio**

### CODE REVIEW

**Comment by rajeshkio** [comment]
There is an issue. I will fix and get back,

**Comment by rajeshkio** [comment]
> There is an issue. I will fix and get back,

Screenshot 2024-12-16 at 16 27 13

3.0.0 is not yet published in the terraform registry. The latest in 2.11.1

**Comment by glovecchi0** [comment]
I confirm.

image

**Comment by glovecchi0** [comment]
The version 3.0.0 is now available.
I'm trying it...

image

**Review by glovecchi0 — APPROVED** [review]
It works well.

image

image
The cluster is starting up.

**Pull request merged**
